export function getCountries() {
  return [
    { code: "af", title: "Afghanistan" },
    { code: "ax", title: "Åland Islands" },
    { code: "al", title: "Albania" },
    { code: "dz", title: "Algeria" },
    { code: "as", title: "American Samoa" },
    { code: "ad", title: "AndorrA" },
    { code: "ao", title: "Angola" },
    { code: "ai", title: "Anguilla" },
    { code: "aq", title: "Antarctica" },
    { code: "ag", title: "Antigua and Barbuda" },
    { code: "ar", title: "Argentina" },
    { code: "am", title: "Armenia" },
    { code: "aw", title: "Aruba" },
    { code: "au", title: "Australia" },
    { code: "at", title: "Austria" },
    { code: "az", title: "Azerbaijan" },
    { code: "bs", title: "Bahamas" },
    { code: "bh", title: "Bahrain" },
    { code: "bd", title: "Bangladesh" },
    { code: "bb", title: "Barbados" },
    { code: "by", title: "Belarus" },
    { code: "be", title: "Belgium" },
    { code: "bz", title: "Belize" },
    { code: "bj", title: "Benin" },
    { code: "bm", title: "Bermuda" },
    { code: "bt", title: "Bhutan" },
    { code: "bo", title: "Bolivia" },
    { code: "ba", title: "Bosnia and Herzegovina" },
    { code: "bw", title: "Botswana" },
    { code: "bv", title: "Bouvet Island" },
    { code: "br", title: "Brazil" },
    { code: "io", title: "British Indian Ocean Territory" },
    { code: "bn", title: "Brunei Darussalam" },
    { code: "bg", title: "Bulgaria" },
    { code: "bf", title: "Burkina Faso" },
    { code: "bi", title: "Burundi" },
    { code: "kh", title: "Cambodia" },
    { code: "cm", title: "Cameroon" },
    { code: "ca", title: "Canada" },
    { code: "cv", title: "Cape Verde" },
    { code: "ky", title: "Cayman Islands" },
    { code: "cf", title: "Central African Republic" },
    { code: "td", title: "Chad" },
    { code: "cl", title: "Chile" },
    { code: "cn", title: "China" },
    { code: "cx", title: "Christmas Island" },
    { code: "cc", title: "Cocos (Keeling) Islands" },
    { code: "co", title: "Colombia" },
    { code: "km", title: "Comoros" },
    { code: "cg", title: "Congo" },
    { code: "cd", title: "Congo, Democratic Republic" },
    { code: "ck", title: "Cook Islands" },
    { code: "cr", title: "Costa Rica" },
    { code: "ci", title: 'Cote D"Ivoire' },
    { code: "hr", title: "Croatia" },
    { code: "cu", title: "Cuba" },
    { code: "cy", title: "Cyprus" },
    { code: "cz", title: "Czech Republic" },
    { code: "dk", title: "Denmark" },
    { code: "dj", title: "Djibouti" },
    { code: "dm", title: "Dominica" },
    { code: "do", title: "Dominican Republic" },
    { code: "ec", title: "Ecuador" },
    { code: "eg", title: "Egypt" },
    { code: "sv", title: "El Salvador" },
    { code: "gq", title: "Equatorial Guinea" },
    { code: "er", title: "Eritrea" },
    { code: "ee", title: "Estonia" },
    { code: "et", title: "Ethiopia" },
    { code: "fk", title: "Falkland Islands (Malvinas)" },
    { code: "fo", title: "Faroe Islands" },
    { code: "fj", title: "Fiji" },
    { code: "fi", title: "Finland" },
    { code: "fr", title: "France" },
    { code: "gf", title: "French Guiana" },
    { code: "pf", title: "French Polynesia" },
    { code: "tf", title: "French Southern Territories" },
    { code: "ga", title: "Gabon" },
    { code: "gm", title: "Gambia" },
    { code: "ge", title: "Georgia" },
    { code: "de", title: "Germany" },
    { code: "gh", title: "Ghana" },
    { code: "gi", title: "Gibraltar" },
    { code: "gr", title: "Greece" },
    { code: "gl", title: "Greenland" },
    { code: "gd", title: "Grenada" },
    { code: "gp", title: "Guadeloupe" },
    { code: "gu", title: "Guam" },
    { code: "gt", title: "Guatemala" },
    { code: "gg", title: "Guernsey" },
    { code: "gn", title: "Guinea" },
    { code: "gw", title: "Guinea-Bissau" },
    { code: "gy", title: "Guyana" },
    { code: "ht", title: "Haiti" },
    { code: "hm", title: "Heard Island and Mcdonald Islands" },
    { code: "va", title: "Holy See (Vatican City State)" },
    { code: "hn", title: "Honduras" },
    { code: "hk", title: "Hong Kong" },
    { code: "hu", title: "Hungary" },
    { code: "is", title: "Iceland" },
    { code: "in", title: "India" },
    { code: "id", title: "Indonesia" },
    { code: "ir", title: "Iran" },
    { code: "iq", title: "Iraq" },
    { code: "ie", title: "Ireland" },
    { code: "im", title: "Isle of Man" },
    { code: "il", title: "Israel" },
    { code: "it", title: "Italy" },
    { code: "jm", title: "Jamaica" },
    { code: "jp", title: "Japan" },
    { code: "je", title: "Jersey" },
    { code: "jo", title: "Jordan" },
    { code: "kz", title: "Kazakhstan" },
    { code: "ke", title: "Kenya" },
    { code: "ki", title: "Kiribati" },
    { code: "kp", title: "Korea (North)" },
    { code: "kr", title: "Korea (South)" },
    { code: "xk", title: "Kosovo" },
    { code: "kw", title: "Kuwait" },
    { code: "kg", title: "Kyrgyzstan" },
    { code: "la", title: "Laos" },
    { code: "lv", title: "Latvia" },
    { code: "lb", title: "Lebanon" },
    { code: "ls", title: "Lesotho" },
    { code: "lr", title: "Liberia" },
    { code: "ly", title: "Libyan Arab Jamahiriya" },
    { code: "li", title: "Liechtenstein" },
    { code: "lt", title: "Lithuania" },
    { code: "lu", title: "Luxembourg" },
    { code: "mo", title: "Macao" },
    { code: "mk", title: "Macedonia" },
    { code: "mg", title: "Madagascar" },
    { code: "mw", title: "Malawi" },
    { code: "my", title: "Malaysia" },
    { code: "mv", title: "Maldives" },
    { code: "ml", title: "Mali" },
    { code: "mt", title: "Malta" },
    { code: "mh", title: "Marshall Islands" },
    { code: "mq", title: "Martinique" },
    { code: "mr", title: "Mauritania" },
    { code: "mu", title: "Mauritius" },
    { code: "yt", title: "Mayotte" },
    { code: "mx", title: "Mexico" },
    { code: "fm", title: "Micronesia" },
    { code: "md", title: "Moldova" },
    { code: "mc", title: "Monaco" },
    { code: "mn", title: "Mongolia" },
    { code: "ms", title: "Montserrat" },
    { code: "ma", title: "Morocco" },
    { code: "mz", title: "Mozambique" },
    { code: "mm", title: "Myanmar" },
    { code: "na", title: "Namibia" },
    { code: "nr", title: "Nauru" },
    { code: "np", title: "Nepal" },
    { code: "nl", title: "Netherlands" },
    { code: "an", title: "Netherlands Antilles" },
    { code: "nc", title: "New Caledonia" },
    { code: "nz", title: "New Zealand" },
    { code: "ni", title: "Nicaragua" },
    { code: "ne", title: "Niger" },
    { code: "ng", title: "Nigeria" },
    { code: "nu", title: "Niue" },
    { code: "nf", title: "Norfolk Island" },
    { code: "mp", title: "Northern Mariana Islands" },
    { code: "no", title: "Norway" },
    { code: "om", title: "Oman" },
    { code: "pk", title: "Pakistan" },
    { code: "pw", title: "Palau" },
    { code: "ps", title: "Palestinian Territory, Occupied" },
    { code: "pa", title: "Panama" },
    { code: "pg", title: "Papua New Guinea" },
    { code: "py", title: "Paraguay" },
    { code: "pe", title: "Peru" },
    { code: "ph", title: "Philippines" },
    { code: "pn", title: "Pitcairn" },
    { code: "pl", title: "Poland" },
    { code: "pt", title: "Portugal" },
    { code: "pr", title: "Puerto Rico" },
    { code: "qa", title: "Qatar" },
    { code: "re", title: "Reunion" },
    { code: "ro", title: "Romania" },
    { code: "ru", title: "Russian Federation" },
    { code: "rw", title: "Rwanda" },
    { code: "sh", title: "Saint Helena" },
    { code: "kn", title: "Saint Kitts and Nevis" },
    { code: "lc", title: "Saint Lucia" },
    { code: "pm", title: "Saint Pierre and Miquelon" },
    { code: "vc", title: "Saint Vincent and the Grenadines" },
    { code: "ws", title: "Samoa" },
    { code: "sm", title: "San Marino" },
    { code: "st", title: "Sao Tome and Principe" },
    { code: "sa", title: "Saudi Arabia" },
    { code: "sn", title: "Senegal" },
    { code: "rs", title: "Serbia" },
    { code: "me", title: "Montenegro" },
    { code: "sc", title: "Seychelles" },
    { code: "sl", title: "Sierra Leone" },
    { code: "sg", title: "Singapore" },
    { code: "sk", title: "Slovakia" },
    { code: "si", title: "Slovenia" },
    { code: "sb", title: "Solomon Islands" },
    { code: "so", title: "Somalia" },
    { code: "za", title: "South Africa" },
    { code: "gs", title: "South Georgia and the South Sandwich Islands" },
    { code: "es", title: "Spain" },
    { code: "lk", title: "Sri Lanka" },
    { code: "sd", title: "Sudan" },
    { code: "sr", title: "Suriname" },
    { code: "sj", title: "Svalbard and Jan Mayen" },
    { code: "sz", title: "Swaziland" },
    { code: "se", title: "Sweden" },
    { code: "ch", title: "Switzerland" },
    { code: "sy", title: "Syrian Arab Republic" },
    { code: "tw", title: "Taiwan, Province of China" },
    { code: "tj", title: "Tajikistan" },
    { code: "tz", title: "Tanzania" },
    { code: "th", title: "Thailand" },
    { code: "tl", title: "Timor-Leste" },
    { code: "tg", title: "Togo" },
    { code: "tk", title: "Tokelau" },
    { code: "to", title: "Tonga" },
    { code: "tt", title: "Trinidad and Tobago" },
    { code: "tn", title: "Tunisia" },
    { code: "tr", title: "Turkey" },
    { code: "tm", title: "Turkmenistan" },
    { code: "tc", title: "Turks and Caicos Islands" },
    { code: "tv", title: "Tuvalu" },
    { code: "ug", title: "Uganda" },
    { code: "ua", title: "Ukraine" },
    { code: "ae", title: "United Arab Emirates" },
    { code: "gb", title: "United Kingdom" },
    { code: "us", title: "United States" },
    { code: "um", title: "United States Minor Outlying Islands" },
    { code: "uy", title: "Uruguay" },
    { code: "uz", title: "Uzbekistan" },
    { code: "vu", title: "Vanuatu" },
    { code: "ve", title: "Venezuela" },
    { code: "vn", title: "Viet Nam" },
    { code: "vg", title: "Virgin Islands, British" },
    { code: "vi", title: "Virgin Islands, U.S." },
    { code: "wf", title: "Wallis and Futuna" },
    { code: "eh", title: "Western Sahara" },
    { code: "ye", title: "Yemen" },
    { code: "zm", title: "Zambia" },
    { code: "zw", title: "Zimbabwe" },
  ];
}
